name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to Team_side_project_pokemon
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HUN_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: BearHumanS
          destination-repository-name: Team_side_project_pokemon
          user-email: ${{ secrets.HUN_EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: main
      - name: Pushes to Pokehub
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CDM_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: cdm1263
          destination-repository-name: Pokehub
          user-email: ${{ secrets.CDM_EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: main
      - name: Pushes to Pokehub
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DICEPT_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: DICEPT
          destination-repository-name: Pokehub
          user-email: ${{ secrets.DICEPT_EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
